### ISSUE TITLE
Addon is not compatible with Vaadin 24

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/IronIconsAddon#23]
This addon uses `com.vaadin.flow.component.icon.IronIcon` which has been removed in Vaadin 24.

**Comment by javier-godoy** [comment]
We will not support Vaadin 24 for this add-on. `iron-icon` itself is obsolete.

**Comment by javier-godoy** [comment]
We should document this in README and Directory

**Comment by paodb** [comment]
- For **Directory** I would do something like [Enahnced Dialog](https://vaadin.com/directory/component/enhanced-dialog). First title to read "DEPRECATED" and then add a sentence/paragraph saying why it is deprecated and then the rest of the description that was already there. Explanation for deprecation: "As Vaadin dropped support for iron-icons, we will not support Vaadin 24+ for this add-on. "

- For **Readme in repo** something similar. See #25
